import React, { useMemo, useCallback, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { showWarning } from "@/components/ui/feedback/Message";
import {
  SearchIconCellRenderer,
  StatusTagRenderer,
} from "@/components/ui/form/AgGrid/cells";

import type { CellValueChangedEvent, IRowNode } from "ag-grid-community";
import { FormAgGrid } from "@/components/ui/form";
import type { ExtendedColDef } from "@/components/ui/form/AgGrid/FormAgGrid";
import { useBcncAcnutRegistStore } from "@/store/fcm/md/partner/BcncAcnutRegist/BcncAcnutRegistStore";
import { useAuthStore } from "@store/com/auth/authStore";
import type { BcncAcnutListResponse } from "@/types/fcm/md/partner/BcncAcnutRegist/BcncAcnutRegist.types";
import {
  INOUT_TYPE,
  INOUT_TYPE_LABEL,
} from "@/components/features/fcm/md/partner/BcncAcnutRegist/Constants/SelectOptions";
import { usePageModal } from "@/hooks/usePageModal";
import { BankCodeInqirePopup } from "@/pages/com/popup";
import type { SelectedBankCode } from "@/pages/com/popup/BankCodeInqirePopup";
import PageModal from "@/components/ui/feedback/Modal";
import { createCheckboxColumn } from "@/components/ui/form/AgGrid/columns/checkboxColumn";

interface BcncAcnutRegistGridProps {
  className?: string;
}

const BcncAcnutRegistGrid: React.FC<BcncAcnutRegistGridProps> = ({
  className,
}) => {
  const { t } = useTranslation();
  const gridData = useBcncAcnutRegistStore((state) => state.gridData);
  const setGridData = useBcncAcnutRegistStore((state) => state.setGridData);
  const setGridApi = useBcncAcnutRegistStore((state) => state.setGridApi);
  const gridApi = useBcncAcnutRegistStore((state) => state.gridApi);
  const lastSearchRequest = useBcncAcnutRegistStore(
    (state) => state.lastSearchRequest
  );
  const currencyCodes = useBcncAcnutRegistStore((state) => state.currencyCodes);
  const fetchCurrencyCodes = useBcncAcnutRegistStore(
    (state) => state.fetchCurrencyCodes
  );
  const user = useAuthStore((state) => state.user);
  const targetNodeRef = React.useRef<IRowNode<BcncAcnutListResponse> | null>(
    null
  );

  const handlePopupReturn = useCallback((data: SelectedBankCode) => {
    const node = targetNodeRef.current;
    if (data && node && node.data) {
      const newData = {
        ...node.data,
        bankCode: data.bankCode || "",
        bankName: data.bankNm || "",
        rowStatus:
          node.data.rowStatus === "C" ? ("C" as const) : ("U" as const),
      };
      node.setData(newData as BcncAcnutListResponse);
    }
  }, []);

  const { openModal, modalProps } = usePageModal(BankCodeInqirePopup, {
    onReturn: handlePopupReturn,
  });

  // ID 생성 함수
  const generateNewId = useCallback(() => {
    if (gridData.length === 0) return 1;
    const maxId = Math.max(
      ...gridData.map((row) => {
        const id = row.id;
        if (typeof id === "number") return id;
        const num = parseInt(String(id), 10);
        return isNaN(num) ? 0 : num;
      })
    );
    return maxId + 1;
  }, [gridData]);

  const createNewRow = useCallback(
    (newId: number | string): BcncAcnutListResponse => {
      return {
        id: newId,
        rowStatus: "C",
        officeId: user?.officeId || "",
        custno: lastSearchRequest?.asCustno || "",
        seq: 0, // Will be generated by backend or handled later
        acctNbr: "",
        bankCode: "",
        bankName: "",
        defaultYn: "N",
        virtualAcctYn: "N",
        depositor: "",
        inoutType: INOUT_TYPE.DEPOSIT,
        remark: "",
        swiftCode: "",
        curr: "",
        docId: "",
        eatKey: "",
      };
    },
    [user?.officeId, lastSearchRequest?.asCustno]
  );

  /* Helper to get current grid data safely */
  const getCurrentGridData = useCallback(() => {
    if (!gridApi) return [];
    const currentData: BcncAcnutListResponse[] = [];
    gridApi.forEachNode((node) => {
      if (node.data) currentData.push(node.data);
    });
    return currentData;
  }, [gridApi]);

  const handleAddRow = useCallback(() => {
    const currentData = getCurrentGridData();
    const newId = generateNewId();
    const newRow = createNewRow(newId);
    setGridData([newRow, ...currentData]);
    // Focus logic is handled by Grid update, or we can add it here if needed
  }, [getCurrentGridData, generateNewId, createNewRow, setGridData]);

  const handleDeleteRow = useCallback(() => {
    if (!gridApi) return;
    const selectedRows = gridApi.getSelectedRows();
    if (selectedRows.length === 0) {
      showWarning("삭제할 행을 선택해주세요.");
      return;
    }

    const currentData = getCurrentGridData();
    const selectedIds = new Set(selectedRows.map((r) => r.id));

    const newData = currentData
      .map((row) => {
        if (!selectedIds.has(row.id)) return row;
        // Logic: Remove 'C', Mark others 'D'
        if (row.rowStatus === "C") return null;
        return { ...row, rowStatus: "D" as const };
      })
      .filter((row): row is BcncAcnutListResponse => row !== null);

    setGridData(newData);
    gridApi.deselectAll();
  }, [gridApi, getCurrentGridData, setGridData]);

  const handleCopyRow = useCallback(() => {
    if (!gridApi) return;
    const selectedRows = gridApi.getSelectedRows();

    if (selectedRows.length === 0) {
      showWarning("복사할 행을 선택해주세요.");
      return;
    }

    // Use current data source
    const currentData = getCurrentGridData();
    let nextId = generateNewId();

    const newRows = selectedRows.map((row) => {
      const newRow = {
        ...row,
        id: nextId,
        rowStatus: "C" as const, // Force status C
        seq: 0, // Reset seq
        defaultYn: "N", // Reset defaultYn to prevent duplicates
      };
      nextId++;
      return newRow;
    });

    setGridData([...currentData, ...newRows]);
  }, [gridApi, getCurrentGridData, setGridData, generateNewId]);

  useEffect(() => {
    fetchCurrencyCodes();
  }, [fetchCurrencyCodes]);

  const columnDefs: ExtendedColDef<BcncAcnutListResponse>[] = useMemo(() => {
    const currencyValues = currencyCodes.map((code) => code.code || "");
    const currencyLabels = currencyCodes.reduce(
      (acc, code) => {
        if (code.code) {
          acc[code.code] = code.name1 || code.code;
        }
        return acc;
      },
      {} as Record<string, string>
    );

    return [
      {
        headerName: "No.",
        width: 50,
        headerAlign: "center",
        bodyAlign: "center",
        pinned: "left",
        filter: false,
        valueGetter: "node.rowIndex + 1",
      },
      {
        headerName: t("상태"),
        field: "rowStatus",
        width: 50,
        pinned: "left",
        excludeFromExcel: true,
        cellRenderer: StatusTagRenderer,
        cellStyle: { textAlign: "center" },
        headerClass: "ag-header-cell-center",
      },
      {
        ...createCheckboxColumn<BcncAcnutListResponse>(t("기준"), "defaultYn", {
          width: 60,
          editable: true,
          onValueChange: (checked, params) => {
            const { node, api, data } = params;
            if (!node || !data || !api) return;

            // Pre-check for In/Out Type
            if (checked && !data.inoutType) {
              showWarning("입/출금 타입을 먼저 지정하세요.");
              // Revert UI if possible, or just don't update data (UI might stay checked until refresh)
              // Since renderer is controlled by data, strictly not updating data should revert check on refresh/redraw
              // Trigger refresh to ensure UI matches data
              api.refreshCells({ rowNodes: [node], columns: ["defaultYn"] });
              return;
            }

            // 1. Mutual Exclusion Logic (Only when setting to true)
            if (checked) {
              const currentId = data.id;
              const currentType = data.inoutType;

              api.forEachNode((otherNode) => {
                if (
                  otherNode.data &&
                  otherNode.data.id !== currentId &&
                  String(otherNode.data.inoutType) === String(currentType) &&
                  otherNode.data.defaultYn === "Y"
                ) {
                  const otherNewStatus =
                    otherNode.data.rowStatus === "C" ? "C" : "U";
                  otherNode.setData({
                    ...otherNode.data,
                    defaultYn: "N", // Uncheck others
                    rowStatus: otherNewStatus,
                  });
                }
              });
            }

            // 2. Update Self
            const newStatus = data.rowStatus === "C" ? "C" : "U";
            node.setData({
              ...data,
              defaultYn: checked ? "Y" : "N",
              rowStatus: newStatus,
            });
          },
        }),
      },
      createCheckboxColumn<BcncAcnutListResponse>(t("가상계좌"), "virtualAcctYn", {
        width: 80,
        editable: true,
        onValueChange: (checked, params) => {
          const { node, data } = params;
          if (!node || !data) return;

          const newStatus = data.rowStatus === "C" ? "C" : "U";
          node.setData({
            ...data,
            virtualAcctYn: checked ? "Y" : "N",
            rowStatus: newStatus,
          });
        },
      }),
      {
        field: "inoutType",
        headerName: t("입_출금"),
        width: 80,
        headerAlign: "center",
        bodyAlign: "center",
        editable: true,
        cellEditor: "agSelectCellEditor",
        cellEditorParams: {
          values: [INOUT_TYPE.DEPOSIT, INOUT_TYPE.WITHDRAWAL],
        },
        refData: INOUT_TYPE_LABEL,
      },
      {
        field: "bankCode",
        headerName: t("은행코드"),
        width: 120,
        headerAlign: "center",
        bodyAlign: "center",
        editable: true,
        cellRenderer: SearchIconCellRenderer,
        cellRendererParams: {
          onSearchClick: (node: IRowNode<BcncAcnutListResponse>) => {
            targetNodeRef.current = node;
            openModal({
              asOfficeId: user?.officeId,
              initialBankCode: node.data?.bankCode,
            });
          },
        },
      },
      {
        field: "bankName",
        headerName: t("은행명"),
        width: 150,
        headerAlign: "center",
        bodyAlign: "center",
        editable: false, // ReadOnly
      },
      {
        field: "curr",
        headerName: t("통화"), // XML: 통화, DTO: 화폐단위
        width: 100,
        headerAlign: "center",
        bodyAlign: "center",
        editable: true,
        cellEditor: "agSelectCellEditor",
        cellEditorParams: {
          values: currencyValues,
        },
        refData: currencyLabels,
      },
      {
        field: "acctNbr",
        headerName: t("계좌번호"),
        width: 200,
        headerAlign: "center",
        bodyAlign: "center",
        editable: true,
      },
      {
        field: "swiftCode",
        headerName: "Swift Code",
        width: 200,
        headerAlign: "center",
        bodyAlign: "left", // XML says left? actually XML textAlign="left" for SWIFT_CODE
        editable: true,
      },
      {
        field: "depositor",
        headerName: t("예금주"),
        width: 200,
        headerAlign: "center",
        bodyAlign: "left",
        editable: true,
      },
      {
        field: "remark",
        headerName: t("비고"),
        width: 200,
        headerAlign: "center",
        bodyAlign: "left",
        editable: true,
        filter: false,
      },
      {
        field: "docId",
        headerName: "Doc Id",
        width: 100,
        headerAlign: "center",
        bodyAlign: "center",
        editable: false,
      },
      {
        field: "eatKey",
        headerName: "Eat Key",
        width: 70,
        headerAlign: "center",
        bodyAlign: "center",
        editable: false,
      },
      // Hidden Key Columns
      {
        field: "officeId",
        hide: true,
        excludeFromExcel: true,
      },
      {
        field: "custno",
        hide: true,
        excludeFromExcel: true,
      },
      {
        field: "seq",
        hide: true,
        excludeFromExcel: true,
      },
    ];
  }, [t, currencyCodes, openModal, user?.officeId]);

  const toolbarButtons = useMemo(
    () => ({
      showAdd: true,
      showCopy: true,
      showDelete: true,
      showExcelDownload: true,
      showExcelUpload: false,
    }),
    []
  );

  const handleCellValueChanged = useCallback(
    (params: CellValueChangedEvent<BcncAcnutListResponse>) => {
      if (!params.data) return;

      // 1. Row Status Update Logic
      if (params.data.rowStatus !== "C" && params.data.rowStatus !== "D") {
        // We assume onCellValueChanged only fires when value actually changes,
        // so we don't strictly need to check newValue !== oldValue here,
        // especially for checkbox booleans vs string status.
        // We just ensure we don't overwrite 'C' or 'D'.
        if (params.data.rowStatus !== "U") {
          const newData = {
            ...params.data,
            rowStatus: "U",
          } as BcncAcnutListResponse;
          params.node.setData(newData);
        }
      }
    },
    []
  );

  return (
    <>
      <FormAgGrid
        className={className}
        rowData={gridData}
        columnDefs={columnDefs}
        showToolbar={true}
        toolbarButtons={toolbarButtons}
        setRowData={setGridData}
        createNewRow={createNewRow}
        onAddRow={handleAddRow}
        onDeleteRow={handleDeleteRow}
        onCopyRow={handleCopyRow}
        onGridReady={(params) => setGridApi(params.api)}
        onCellValueChanged={handleCellValueChanged}
        pagination={false}
      />
      <PageModal {...modalProps} />
    </>
  );
};

export default BcncAcnutRegistGrid;
